apiVersion: v1
kind: ServiceAccount
metadata:
  name: enclaved
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enclaved
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: enclaved
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: enclaved
subjects:
  - kind: ServiceAccount
    name: enclaved
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: enclaved
  name: enclaved
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: enclaved
  template:
    metadata:
      labels:
        app: enclaved
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      containers:
        - env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: registry.cn-hangzhou.aliyuncs.com/sandboxed-container/enclaved:v0.1.0
          imagePullPolicy: IfNotPresent
          name: enclaved
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: enclaved
      serviceAccountName: enclaved
      volumes:
        - hostPath:
            path: /etc/localtime
            type: File
          name: localtime