name: Compile check

# Controls when the action will run. Triggers the workflow on push or pull request
on: [push, pull_request]

jobs:
  Compile:
    runs-on: ubuntu-18.04
    container: inclavarecontainers/test:${{ matrix.tag }}
    strategy:
      matrix:
        tag: [compile-check-ubuntu18.04, compile-check-centos8.1]
    steps:
    - uses: actions/checkout@v1

    - name: Get cpu number
      run: echo "CPU_NUM=$(nproc --all)" >> $GITHUB_ENV

    - name: Compile "rune shim-rune sgx-tools epm pal"
      run: cd $GITHUB_WORKSPACE;
        make -j${CPU_NUM} && make install -j${CPU_NUM};
        cd rune/libenclave/internal/runtime/pal/skeleton && make -j${CPU_NUM} && ls liberpal-skeleton-v*.so;
        cd ../nitro_enclaves && make -j${CPU_NUM} && ls libpal_ne.so;
        which rune epm containerd-shim-rune-v2 sgx-tools
