name: Build centos image for rune and docker 

on:
  workflow_dispatch:
    inputs:
      occlum_version:
        description: 'The version of Occlum image'
        required: true

jobs:
  generate-centos-image:
      # GitHub Actions doesn't have CentOS VM provided
      runs-on: ubuntu-18.04

      steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build images
        run: cd $GITHUB_WORKSPACE/.github/workflows/docker;
          sed -i "s/OCCLUM_VERSION/${{ github.event.inputs.occlum_version }}/" Dockerfile-centos8.1;
          docker build . -t crictl-centos8.1 -f Dockerfile-centos8.1

      # Dockerfile doesn't support start up containerd
      - name: Download various images in advance to speed up testing
        run: |
          docker run -itd --privileged --name=centos crictl-centos8.1;
          docker exec centos bash -c "containerd" &
          docker exec centos bash -c "crictl pull registry.cn-hangzhou.aliyuncs.com/acs/pause-amd64:3.1;
          crictl pull docker.io/inclavarecontainers/occlum-hello-world:scratch;
          crictl pull docker.io/inclavarecontainers/occlum-dragonwell-web:scratch;
          crictl pull docker.io/inclavarecontainers/occlum-java-web:scratch;
          crictl pull docker.io/inclavarecontainers/occlum-golang-web:0.16.0-scratch"
          docker exec centos bash -c "pkill -9 containerd"
          docker commit centos inclavarecontainers/test:centos8.1-occlum-${{ github.event.inputs.occlum_version }}

      - name: Push crictl image to Dockerhub
        run: docker login -p ${{ secrets.DOCKER_PASSWORD }} -u ${{ secrets.DOCKER_USERNAME }};
          docker push inclavarecontainers/test:centos8.1-occlum-${{ github.event.inputs.occlum_version }}
